#!/bin/bash

./obj/development/test_registers
if [ $? -ne 0 ]
then
   echo "test_registers: FAILED"
else
   echo "test_registers: PASSED"
fi

./obj/development/test_instructions
if [ $? -ne 0 ]
then
   echo "test_instructions: FAILED"
else
   echo "test_instructions: PASSED"
fi

./obj/development/test_decoder
if [ $? -ne 0 ]
then
   echo "test_decoder: FAILED"
else
   echo "test_decoder: PASSED"
fi
